---
  name: Windows Smoke Test
   
  run-name: ${{ github.actor }} is running smoke tests
  on:
    pull_request:
    workflow_dispatch:
  
  jobs:
    Smoke-Windows:
      runs-on: windows-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Set up Python 3.11
          uses: actions/setup-python@v5
          with:
            python-version: "3.11"
        # - name: Install dependencies
        #   run: |
        #     mkdir -p artifacts;
        #     pip3 install 'pipenv==2023.11.15';
        #     pip3 install 'ruff>=0.4.8,<0.5';
        #     rm ./pyproject.toml;
        #     mv ./ci_pyproject.toml ./pyproject.toml;
        #     pipenv install;
        - name: Download Geckodriver
          run: |
            Invoke-WebRequest -Uri "https://github.com/mozilla/geckodriver/releases/download/v0.35.0/geckodriver-v0.35.0-win64.zip" -OutFile "geckodriver.zip"
            unzip geckodriver.zip
          shell: pwsh
        - name: Download Beta
          run: |
            Invoke-WebRequest -Uri "https://download.mozilla.org/?product=firefox-beta-latest-ssl&os=win64&lang=en-US" -OutFile "${{ github.workspace }}\setup.exe"
            New-Item -ItemType Directory -Path "C:\Program Files\Custom Firefox" -Force
          shell: pwsh
        - name: Install Beta
          run: |
            echo "Starting Firefox installation..."
            $exitcode = Start-Process -FilePath "${{ github.workspace }}\setup.exe" -ArgumentList "/S", '/D=C:\Program Files\Custom Firefox' -Wait -NoNewWindow -PassThru
            if ($exitcode -eq 0) {
              echo "Firefox installation completed."
            } else {
              echo "Firefox installation failed."
            }
          shell: pwsh
        - name: Verify installation directory
          run: |
            if (Test-Path "C:\Program Files\Custom Firefox") {
              echo "Installation directory exists."
            } else {
              echo "Installation directory does not exist."
              exit 1
            }
          shell: pwsh
  
        - name: List installed files
          run: |
            if (Test-Path "C:\Program Files\Custom Firefox") {
              Get-ChildItem "C:\Program Files\Custom Firefox" -Recurse
            } else {
              echo "Installation directory does not exist."
            }
          shell: pwsh
  
        - name: Verify Firefox executable
          run: |
            if (Test-Path "C:\Program Files\Custom Firefox\firefox.exe") {
              echo "Firefox executable exists."
            } else {
              echo "Firefox executable does not exist."
            }
          shell: pwsh
  
        - name: Check Firefox version
          run: |
            $version = Get-Item -Path "C:\Program Files\Custom Firefox\firefox.exe" | Select-Object -ExpandProperty VersionInfo
            $version.FileVersion
          shell: pwsh